### ISSUE TITLE
DevOps/Sysadmin: Set up app auto-restart on reboot

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#10]

**Comment by joeflack4** [comment]
@ShahimEssaid I checked and you're an admin on this repo. But for some reason I can't 'assign' this one to you.

**Comment by ShahimEssaid** [comment]
Working and wiil document here: https://docs.google.com/document/d/12L8hAx2G1HvoasBXkxA0WSNZzr2gvlQ0r7E4NRXbOkA/edit#f
