### ISSUE TITLE
tims-ui updates?

### ISSUE THREAD

**Issue by Leskena2** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#103]

**Comment by Leskena2** [comment]
HAPI server has its own UI but does not give you individual concept creations

**Comment by joeflack4** [comment]
Closing this as this is no longer being worked on, and I'm not sure if any updates for it will ever be planned.

I have added it to the [projects page](https://hot-ecosystem.github.io/tims/projects/) on the website though.
