### ISSUE TITLE
TIMS home page (GitHub static page)

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#111]

**Comment by ShahimEssaid** [comment]
Initial setup done here: https://github.com/HOT-Ecosystem/tims/tree/gh-pages

See https://hot-ecosystem.github.io/tims/

**Comment by joeflack4** [comment]
That was fast. That's awesome.

I wonder what's best without too much complicated setup. When people go to the domain through the browser, does it route to this? But if it's a programmatic request, so to speak, it goes to the API. Not sure.

Maybe we can come up with some verbiage together at a meeting. I think we can keep it simple.

We could potentially use this as inspiration. I think the verbiage here is very close to what was published on hotecosystem.org: https://github.com/HOT-Ecosystem/server

**Comment by ShahimEssaid** [comment]
I'll add the custom domain when we have it. We'll use a subdomain for the GH site and leave the top domain free to not tie it to any specific IP. That way, we keep creating subdomains as needed for the different "systems" we have.  The FHIR server will have its own subdomain record so we can move that around as needed.  Either do that way, or setup a proxy server somewhere that proxies or redirects different locations under one (sub)domain.  See the GH docs here: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by ShahimEssaid** [comment]
I think the home page can have general language about our group. We'll create different pages for the different activities and assign an "editor" as the main person that knows how to keep that page up to date with the ongoing activities.  I think we can use this site for documentation as well. See an example here (the docs for the theme we're using): https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
