### ISSUE TITLE
HAPI version update: 5.7 -> 6.1

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#30]

**Comment by chrisroederucdenver** [comment]
What does this buy us? What does it cost us? Have we given the new version a test run? Does it involve breaking changes?

**Comment by joeflack4** [comment]
I think @ShahimEssaid has looked into it and noticed some updates he thought were nice, but I don't know the detail. I don't see any patch notes [here](https://github.com/hapifhir/hapi-fhir/releases), but they're probably somewhere. It looks like it's using semver, so should be some breaking changes, but DK what they are. In terms of cost, nothing monetary of course. I think Shahim is also in the middle of trying to upgrade our codebase to this.

**Comment by chrisroederucdenver** [comment]
I quite often consider non-monetary costs. For example, if a major revision requires major change to code that consumes an API, upgrading costs you having to do those changes. If  there is some super useful functionality in the new version, then the cost/benefit is probably a win. Of course, if you don't need it, then there is not as much a rush. We might be short on time so we need to pick our battles.

As far as closing this. It's abstract enough that it doesn't end with an addition to the testing notebook.

**Comment by chrisroederucdenver** [comment]
OK, upgrading to HAPI 6.1 is included in the Docker (for mac) stuff I did.  
(edit 11/28) I backed off to a 5.x release because I couldn't get 6.x running fully.
