### ISSUE TITLE
Systems Architecture of Connectathon

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#44]
We've discussed some of this under the infrastructure ticket where we mention the URL, URL extension, #39 
More under #42 for having a stable location for FHIR CodeSystem files.
see also #35 about batch operations (which I think are more like RDBMS transactions than downloading a whole terminology)

Here I'm interested in how different kinds of software brought to a connectathon actually interact. What software will come to interconnect? Will everyone be running HAPI for example? If someone has a FHIR server for clinical data and interaction with it requries a terminology server, do the terminologies (CodeSystem, ValueSet, CocneptMapt, etc) have to be loaded locally, or will they hit a HAPI server dedicated to that task? Does this work for other software packages.

It's a wide open topic.

**Comment by joeflack4** [comment]
For software, I've seen TouchStone and Conman, which are web clients, roughly. Maybe the next Connectathon will be different, but from what I've seen from the last 3, you can just bring your own server and run test scripts on your own (via these web apps), and then other people are there to support you if you need help. I would be happy if the next Connectathon (terminology track or otherwise) would engage servers / devs a little bit more.

**Comment by chrisroederucdenver** [comment]
I thought TouchStone was like an automated client that would hammer your server and produce a report.

The sense I have for our role in Jan. is as infrastructure provider where folks don't have to load their own vocabularies because there is a well-stocked terminology server available. That's us. And it really means we have to know what folks will need and want.

**Comment by joeflack4** [comment]
Regarding touchstone, it is a client, and it does let you run TestScripts and produces a report. However from what I've seen, you manually select and run the TestScripts. There may be a feature to do this in some automatic fashion (on code push, or 1x/daily, etc), but if so, that feature might be behind a paywall; not sure.

Regarding the connectathon and the terminology server, I don't disagree that this is a good goal. I just don't know when/if to expect that scenario. I've been to 3 connectathons so far, and I haven't heard or seen anyone sharing any information about their own terminology servers. It's the right place to do it, though. Maybe this will be different in the future. I certainly enjoy my work more when other people can make use of it.

**Comment by chrisroederucdenver** [comment]
You studied philosophy right? Black Swans. 

The idea of an infrastructure isn't coming from me.

**Comment by joeflack4** [comment]
Yep, you're right, I did! Yeah, definitely this could change in the future. I hope it does. I would like to feel more like I'm engaged in collaboration at the connectathon, and I would certainly love if others found our server useful.

**Comment by chrisroederucdenver** [comment]
For the January Connectathon at least, there basically isn't a systems architecture in the sense of collaborating software systems. So far, it looks like the interaction will be human, not an application hitting a server, or some kind of server federation.

**Comment by chrisroederucdenver** [comment]
human interaction for Jan. RWD Connectathon confirmed. Ticket is moot.
