### ISSUE TITLE
Demo Environment: Jupyter Notebook

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#47]
We need to test and show that various things work using HAPI-FHIR. Many, if not most, are documented that they should work. For those, the task is less test and more demo. Things like $lookup a concept by it's coding. Others, like text search involve more work. I think we have to do some work to enable lucene search and wire it up. That needs tested. Both, at the end of the day need a tiny little Demo.

I started the process with my collection of BASH/cURL scripts that evolved into Postman scripts. I like BASH/cURL becuase we can script it. With a little jq at the end, we can make it readable.

Joe has a great idea to build a Jupyter notebook. If it uses requests, the URLs used to access the API will be in the code and we can generate something a little more readable. We should verify that a Jupyter notebook can be run from a script or as a CLI so we can drive this by google actions. As we build our HAPI config and data load, we can re-run the notebook to show more and more capability working. It will also verify any new config didn't break anything.

**Comment by chrisroederucdenver** [comment]
I have a [start out there]( https://github.com/HOT-Ecosystem/TSDemoBoard/blob/master/CodeSystem.ipynb ).

There's a second ticket for adding more resources and operations. This one should continue with considering issues about what it should show, how much better looking it could be, and how to deploy it.

I've seen were RStudio has Rmd's that get "knit" into PDFs or HTML. You can direct it to hide the code and have something really, really readable, so I wondered how to do it here. After committing this work, it looks like that is a low-complexity method. The committed notebook has output in it. Depending on our audience or their reception, it could be enough. Def. open to opinions and suggestions.

**Comment by chrisroederucdenver** [comment]
Also, I should add issue numbers/links to the section titles. Since that is kind of the point of this.

**Comment by joeflack4** [comment]
Yeah, outputting in those formats is my idea too. I didn't know you could hide code cells while doing that, but that may be advisable sometimes. What I try to do with these is if I need to write a lot of code to do something, I put import that from elsewhere (e.g. a second Python file that goes with it), and then try to keep the code cells to one-liners. 

Very good idea to use markdown hyperlinks to link to issues!

**Comment by chrisroederucdenver** [comment]
You can hide cells/blocks in RStudio, not sure if or how in Jupyter. It's not so much hiding the cells in the notebook as a programmer sees it, but in the generated (knit) PDF that a consumer would see. 

I like the lib/package/file idea to hide the gnarly code. I started some of that with that first section that has the "decode" functions.  Some of them are wired so they show the URL from the request followed by output.  I hope we can get it clean enough by Friday to show it to Melissa and Chris to see if they gag reading URLs or  not. ;-)  If so, we'll need to polish a bit more.  It's fun coding, but I think your Python is def. stronger than my own, so please criticize and suggest. If you want to hack on it, don't mind me.  I'm on N3C stuff at the moment.

**Comment by joeflack4** [comment]
@chrisroederucdenver Guessing you mean next Friday? I actually sent an email to Chris suggesting this, but he hasn't yet understood exactly what I meant. But when we share, I think he'll get it immediately.

I can help on this some time next week. Tuesday probably good. So whatever you have done by then, I can pick up where you left off. I don't care too much about writing "good / standard Python" at this time, especially since that'll be tucked away in a separate file, but I will likely have suggestions.

**Comment by chrisroederucdenver** [comment]
I added CodeSystemTest.ipynb so we can more thoroughly test using the same infrastructure without cluttering the demo page, which is the original CodeSystem.ipynb.  We can continue the naming convention with the other resources in the CRUD ticket.

**Comment by joeflack4** [comment]
Calling this one good!
