### ISSUE TITLE
Phenopackets focus on C-thon 32

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#49]
(Like a sub-issue of #48) 

Focus on the Phenopackets and Genomics tracks because we know them and describe what resources (little r) they would require of either a terminology server or a clinical data server.

For example, if we did a repeat of the September Phenopackets track, what terminology Resources would have to be loaded into a terminology server for it to run it's validation?

Are there elements of the bigger workflow and roles where a user would query a terminology server directly? Consider a UI or scripts that mimic the queries a user would make....and write the scripts for automated tests anyway.

**Comment by joeflack4** [comment]
From today's TIMS meeting (paraphrasing):
Melissa:
> Will get needs from Vulcan meeting.

Shahim:
> We should look at the IG to find needs and support them.

**Comment by chrisroederucdenver** [comment]
ChrisC: we should not lose site of general HL7 clinical focus.

**Comment by chrisroederucdenver** [comment]
Moved to notes
