### ISSUE TITLE
Jan Connectathon: Get needs for Vulcan

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#54]
Will get needs from Vulcan meeting.

Shahim: We should look at the IG to find needs and support them.

**Comment by joeflack4** [comment]
Closing this as I think is redundant with #49

**Comment by chrisroederucdenver** [comment]
Not completed, but duplicate.

**Comment by chrisroederucdenver** [comment]
reopen so I can try and complete it as a duplicate.
