### ISSUE TITLE
Jan Connectathon: Support for genomics track?

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#55]
Shahim: We should look at the IG to find needs and support them.

**Comment by chrisroederucdenver** [comment]
Moved to the project notes google doc.
https://docs.google.com/document/d/1XMnd-ov6kcoe4YdBrY4GZATlBuJzhB3Fxq3lyDaFfKg/edit#

**Comment by chrisroederucdenver** [comment]
moved to a google doc
https://docs.google.com/document/d/1XMnd-ov6kcoe4YdBrY4GZATlBuJzhB3Fxq3lyDaFfKg/edit#
