### ISSUE TITLE
Mondo on FHIR

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#65]
- [x] 1. (initial version completed using `fhir-owl`, but needs improvement)
- [ ] 2. Tweak to make better
- [ ] 3. Unit tests
- [ ] 4. Any entry needed in Jupyter? (probably not)

**Comment by chrisroederucdenver** [comment]
Could have labelled this an "easy" version, meaning we bring over concepts and synonyms.  fhir-owl is bringing over CHEBI terms that are in the MONDO OWL file. Simple test cases are in the CodeSystemTest Jupyter file.

A build.sh script to fetch and convert the ontology is checked in.
