### ISSUE TITLE
Reference Terminology Sources

### ISSUE THREAD

**Issue by DaveraGabriel** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#8]
Hello All:

I'll leave some notes / links here re: terminology "sources of truth."  Maybe there will be other reference terminology resources we can add to this issue.  But I wanted anchor some comments Ive been making in some endpoints for you folks to take a look

SNOMED CT US edition: https://www.nlm.nih.gov/healthit/snomedct/us_edition.html
SNOMED CT International Edition: https://www.nlm.nih.gov/healthit/snomedct/international.html

ICD10CM: https://www.cms.gov/medicare/icd-10/2022-icd-10-cm
ICD10PCS: https://www.cms.gov/medicare/icd-10/2022-icd-10-pcs

RxNorm: https://www.nlm.nih.gov/research/umls/rxnorm/docs/rxnormfiles.html

LOINC: https://loinc.org/downloads/

HCPCS Level 2 (substitute for CPT): https://www.cms.gov/Medicare/Coding/MedHCPCSGenInfo

**Comment by joeflack4** [comment]
Closing as is redundant w/ #4, but thank you! I added this information to that issue.
