### ISSUE TITLE
tims-hapi-terminology-server HAPI instance

### ISSUE THREAD

**Issue by ShahimEssaid** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#84]
An issue to track progress for setting up the [tims-hapi-terminology-server](https://github.com/HOT-Ecosystem/tims-hapi-terminology-server) repositoy to host the terminology server on our VM.

**Comment by ShahimEssaid** [comment]
- A HAPI isntance is running at http://20.3.198.176:18080
- It is based on HAPI code built from https://github.com/HOT-Ecosystem/tims-hapi-build/tree/dev
- It is ran with a checkout of the TIMS HAPI copose setup from: https://github.com/HOT-Ecosystem/tims-hapi-terminology-server/tree/dev
- There are 1 or 2 local config files on the VM (but git ignored) to configure VM specific settings.
- The HAPI instance is rebuilt and redeplyed through GH Actions whenever there is a new push to the dev branch of the HAPI code listed above, or a push to the dev branch of: https://github.com/ShahimEssaid/hapi-extensions/tree/dev.  The latter repository provides general HAPI extensions that are used in our TIMS HAPI code and therefore it triggers a rebuild as well.

**Comment by joeflack4** [comment]
@ShahimEssaid This is done I think right? If so can you close?

Or if it's ongoing we can move it to the new "Ongoing" section we just added to the board.

**Comment by joeflack4** [comment]
Gonna close this since the server is up.

If we need to put notes about the server somewhere, I'm fine with this, but somewhere else is probably better, like a wiki maybe, or a discussion thread, or a google doc.
