### ISSUE TITLE
HAPI CodeSystem text search implementation

### ISSUE THREAD

**Issue by ShahimEssaid** [HOT-Ecosystem/hapi-fhir-jpaserver-starter#92]

**Comment by ShahimEssaid** [comment]
The previous demo is [here](https://github.com/ShahimEssaid/hapi-extensions/blob/dev/src/main/java/com/essaid/fhir/hapi/ext/provider/CodeSystemConceptSearchOperation.java) but is being refactored into the new setup for a TIMS specific HAPI code base [found here](https://github.com/HOT-Ecosystem/tims-hapi-build/tree/v6.4.0_tims)

**Comment by ShahimEssaid** [comment]
The text search demo, as is, has been moved to the dev branch of [tims-hapi-build](https://github.com/HOT-Ecosystem/tims-hapi-build/tree/dev) for further development.

**Comment by joeflack4** [comment]
Replacing this with #46, though we could potentially consider #46 as a grouping issue for all text search related stuff (implementation, specification, testing) and this to just be a subcomponent of that. If we choose to do that we can re-open.
